# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
